"""nullable end of membership

Revision ID: f1350f85f845
Revises: 69fa36be3a32
Create Date: 2024-12-07 09:49:14.056205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1350f85f845'
down_revision = '69fa36be3a32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('membership', schema=None) as batch_op:
        batch_op.alter_column('membership_end',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('membership', schema=None) as batch_op:
        batch_op.alter_column('membership_end',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
